#!/bin/bash
#		•==========•		#
#SHELL颜色
#	•====[重置]====•	#
COLOR_OFF='\033[0m'			# 重置
#	•====[常规]====•	#
BLACK='\033[0;30m'			# 黑色
RED='\033[0;31m'			# 红色
GREEN='\033[0;32m'			# 绿色
YELLOW='\033[0;33m'			# 黄色
BLUE='\033[0;34m'			# 蓝色
PURPLE='\033[0;35m'			# 紫色
CYAN='\033[0;36m'			# 青色
WHITE='\033[0;37m'			# 白色
#	•====[粗体]====•	#
BBLACK='\033[1;30m'			# 黑色
BRED='\033[1;31m'			# 红色
BGREEN='\033[1;32m'			# 绿色
BYELLOW='\033[1;33m'		# 黄色
BBLUE='\033[1;34m'			# 蓝色
BPURPLE='\033[1;35m'		# 紫色
BCYAN='\033[1;36m'			# 青色
BWHITE='\033[1;37m'			# 白色
#	•====[下划线]====•	#
UBLACK='\033[4;30m'			# 黑色
URED='\033[4;31m'			# 红色
UGREEN='\033[4;32m'			# 绿色
UYELLOW='\033[4;33m'		# 黄色
UBLUE='\033[4;34m'			# 蓝色
UPURPLE='\033[4;35m'		# 紫色
UCYAN='\033[4;36m'			# 青色
UWHITE='\033[4;37m'			# 白色
#	•====[背景]====•	#
ON_BLACK='\033[40m'			# 黑色
ON_RED='\033[41m'			# 红色
ON_GREEN='\033[42m'			# 绿色
ON_YELLOW='\033[43m'		# 黄色
ON_BLUE='\033[44m'			# 蓝色
ON_PURPLE='\033[45m'		# 紫色
ON_CYAN='\033[46m'			# 青色
ON_WHITE='\033[47m'			# 白色
#		•==========•		#


API_URL="http://192.168.0.1:9090/goform/goform_get_cmd_process?cmd=getAllDeviceInfo"
# 使用curl命令获取JSON数据
getbin=$(curl -s "$API_URL")

# 检查是否成功获取到JSON数据
if [ -z "$getbin" ]; then
  echo -e "[${RED}ERROR${COLOR_OFF}]无法获取设备信息"
  exit 1
else
 echo -e "[${GREEN}OK${COLOR_OFF}]GET API"
 echo •==========•
fi
#		计算
rateup=$(echo "scale=0; $(echo $getbin | jq -r '.rateup') / 1" | bc)
ratedown=$(echo "scale=0; $(echo $getbin | jq -r '.ratedown') / 1" | bc)
dataup=$(echo "scale=2; $(echo $getbin | jq -r '.dataup') / 1024" | bc)
datadown=$(echo "scale=2; $(echo $getbin | jq -r '.datadown') / 1024" | bc)
#		•==========•		#

#		值
device="$(echo $getbin | jq -r .device)"
devtype="$(echo $getbin | jq -r .devtype)"
version="$(echo $getbin | jq -r .version)"
verfw="$(echo $getbin | jq -r .verfw)"
uptime="$(echo $getbin | jq -r .uptime)"
battery="$(echo $getbin | jq -r .battery)"
batlevel="$(echo $getbin | jq -r .batlevel)"
charging="$(echo $getbin | jq -r .charging)"
discharging="$(echo $getbin | jq -r .discharging)"
voltage="$(echo $getbin | jq -r .voltage)"
imei="$(echo $getbin | jq -r .imei)"
imsi="$(echo $getbin | jq -r .imsi)"
ispid="$(echo $getbin | jq -r .ispid)"
rsigdbm="$(echo $getbin | jq -r .rsigdbm)"
sigtype="$(echo $getbin | jq -r .sigtype)"
wifissid="$(echo $getbin | jq -r .wifissid)"
wifipwd="$(echo $getbin | jq -r .wifipwd)"
ssidhide="$(echo $getbin | jq -r .ssidhide)"
wifimode="$(echo $getbin | jq -r .wifimode)"
dns1="$(echo $getbin | jq -r .dns1)"
dns2="$(echo $getbin | jq -r .dns2)"
clients="$(echo $getbin | jq -r .clients)"
clients="$(echo $getbin | jq -r .clients)"
powermode="$(echo $getbin | jq -r .powermode)"
logEnable="$(echo $getbin | jq -r .logEnable)"
#		•==========•		#

#		输出
echo -e "${BBLUE}WiFi信息${COLOR_OFF}："
echo -e "• ${GREEN}SSID${COLOR_OFF}:		${YELLOW}${wifissid}${COLOR_OFF}"
echo -e "• ${GREEN}PWD${COLOR_OFF}:		${YELLOW}${wifipwd}${COLOR_OFF}"
echo -e "• ${GREEN}HIDE${COLOR_OFF}:		${YELLOW}${ssidhide}${COLOR_OFF}"
echo -e "• ${GREEN}Wi-Fi频段${COLOR_OFF}:	${YELLOW}${wifimode}  ${PURPLE}[${COLOR_OFF}${CYAN}0${COLOR_OFF}：${YELLOW}2.4Ghz${COLOR_OFF}、${CYAN}1${COLOR_OFF}：${YELLOW}5.8Ghz${COLOR_OFF}${PURPLE}]${COLOR_OFF}"
echo -e •==========•
qrencode -t ansiutf8 "WIFI:T:WPA;S:${wifissid};P:${wifipwd};H:false;"